export const CUSTOMER_ID_SELECTED = 'CUSTOMER_ID_SELECTED';
export const PAPER_SIZE_ID_SELECTED = 'PAPER_SIZE_ID_SELECTED';
export const PAPER_GSM_ID_SELECTED = 'PAPER_GSM_ID_SELECTED';
export const PAPER_ITEM_ID_SELECTED = 'PAPER_ITEM_ID_SELECTED';
export const JOB_ID_SELECTED = 'JOB_ID_SELECTED';
export const ALL_JOBS_ID_SELECTED = 'ALL_JOBS_ID_SELECTED';